trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: $(gitVersionVersion)
    includePrerelease: true

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'git-version.yml'

- script: 'git push https://$(GitHubToken)@github.com/templafy/AppConnectorLibrary.git'
  displayName: Push to GitHub
