trigger:
  branches:
    include:
    - master

pool:
  vmImage: $(agentPoolVmImage)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

steps:
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.3.7'
    useConfigFile: true
    configFilePath: 'git-version.yml'

- script: yarn install
  workingDirectory: ./examples/app-connector
  displayName: 'Yarn install'

- script: yarn build
  workingDirectory: ./examples/app-connector
  displayName: 'Yarn build'

- script: 'git push https://$(GitHubToken)@github.com/templafy/AppConnectorLibrary.git'
  displayName: Push to GitHub
