trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

resources:
  repositories:
  - repository: templates
    name: Pipelines
    type: git
    ref: refs/tags/0.12.77

steps:
- template: pipeline-templates/gitversion-task.yml@templates
  parameters:
    gitVersionVersion: $(gitVersionVersion)

- script: 'git push https://$(GitHubToken)@github.com/templafy/AppConnectorLibrary.git'
  displayName: Push to GitHub
