trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

- template: pipeline-templates/gitversion-task.yml@templates
    parameters:
      gitVersionVersion: $(gitVersionVersion)

- script: 'git push https://$(GitHubToken)@github.com/templafy/AppConnectorLibrary.git'
  displayName: Push to GitHub
