trigger:
  branches:
    include:
    - master

pool:
  name: $(agentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.3.7'

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'git-version.yml'

- script: yarn install
  workingDirectory: ./examples/app-connector
  displayName: 'Yarn install'

- script: yarn build
  workingDirectory: ./examples/app-connector
  displayName: 'Yarn build'

- script: 'git push https://$(GitHubToken)@github.com/templafy/AppConnectorLibrary.git'
  displayName: Push to GitHub
